[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python -m backend.seed_data && python main.py"

[plugins.postgresql]
enabled = true

[environments.production]
variables = { ENVIRONMENT = "production", DATABASE_URL = "${{postgresql.DATABASE_URL}}" }
